initial_positions:
  left_front_wheel_joint: 0.0
  left_middle_wheel_joint: 0.0
  left_rear_wheel_joint: 0.0
  right_front_wheel_joint: 0.0
  right_middle_wheel_joint: 0.0
  right_rear_wheel_joint: 0.0
