#ifndef SILVERHAND_ROVER_HARDWARE__VISIBILITY_CONTROL_H_
#define SILVERHAND_ROVER_HARDWARE__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define SILVERHAND_ROVER_HARDWARE_EXPORT __attribute__ ((dllexport))
    #define SILVERHAND_ROVER_HARDWARE_IMPORT __attribute__ ((dllimport))
  #else
    #define SILVERHAND_ROVER_HARDWARE_EXPORT __declspec(dllexport)
    #define SILVERHAND_ROVER_HARDWARE_IMPORT __declspec(dllimport)
  #endif
  #ifdef SILVERHAND_ROVER_HARDWARE_BUILDING_DLL
    #define SILVERHAND_ROVER_HARDWARE_PUBLIC SILVERHAND_ROVER_HARDWARE_EXPORT
  #else
    #define SILVERHAND_ROVER_HARDWARE_PUBLIC SILVERHAND_ROVER_HARDWARE_IMPORT
  #endif
  #define SILVERHAND_ROVER_HARDWARE_PUBLIC_TYPE SILVERHAND_ROVER_HARDWARE_PUBLIC
  #define SILVERHAND_ROVER_HARDWARE_LOCAL
#else
  #define SILVERHAND_ROVER_HARDWARE_EXPORT __attribute__ ((visibility("default")))
  #define SILVERHAND_ROVER_HARDWARE_IMPORT
  #if __GNUC__ >= 4
    #define SILVERHAND_ROVER_HARDWARE_PUBLIC __attribute__ ((visibility("default")))
    #define SILVERHAND_ROVER_HARDWARE_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define SILVERHAND_ROVER_HARDWARE_PUBLIC
    #define SILVERHAND_ROVER_HARDWARE_LOCAL
  #endif
  #define SILVERHAND_ROVER_HARDWARE_PUBLIC_TYPE
#endif

#endif  // SILVERHAND_ROVER_HARDWARE__VISIBILITY_CONTROL_H_

